---
documentclass: moderncv
classoption: [11pt,letterpaper]
output:
  pdf_document:
    includes:
      in_header: assets/tex/preamble.tex
    keep_tex: yes
    number_sections: no
    latex_engine: xelatex
    template: assets/tex/my_template.tex
---

```{r}
#| label: setup 
#| include: false
Sys.setenv(TEXINPUTS = ".:./assets/tex:")
```

```{r}
#| label: download-refs
#| echo: false
#| cache: false
#| warning: false
#| eval: false
library("RefManageR")
library("here")

# Set bib file url
fileUrl <- "https://raw.githubusercontent.com/jvcasillas/mybib/master/publications_latex.bib"

# Download bib file 
download.file(
  fileUrl, 
  cacheOK = F, 
  destfile = here("assets", "bib", "publications_latex.bib"), 
  method = "curl"
)

# Load bib file 
bib <- ReadBib(here("assets", "bib", "publications_latex.bib"), check = FALSE)
```

```{r}
#| label: fix-color-incompatibilities
#| echo: false
#| eval: false
# This may now be irrelevant after editing /tex/moderncv.cls but leaving
# just in case
library("knitr")
knit_hooks$set(document = function(x) {sub('\\usepackage[]{color}', '\\usepackage[table]{xcolor}', x, fixed = TRUE)})
```

```{r}
#| label: insert-set-fonts
#| child: './assets/sections/set_fonts.Rmd'
```

```{r}
#| label: insert-make-title
#| child: './assets/sections/make_title.Rmd'
```

```{r}
#| label: insert-address-block
#| child: './assets/sections/address_block.Rmd'
```

```{r}
#| label: insert-appointments
#| child: './assets/sections/appointments.Rmd'
```

```{r}
#| label: insert-education
#| child: './assets/sections/education.Rmd'
```

```{r}
#| label: insert-publications
#| child: './assets/sections/publications.Rmd'
```

```{r}
#| label: insert-software
#| child: './assets/sections/software.Rmd'
```

```{r}
#| label: insert-presentations
#| child: './assets/sections/presentations.Rmd'
```

```{r}
#| label: insert-research-experience
#| child: './assets/sections/research_experience.Rmd'
```

```{r}
#| label: insert-academic-accolates
#| child: './assets/sections/academic_accolades.Rmd'
```

```{r}
#| label: insert-teaching-experience
#| child: './assets/sections/teaching_experience.Rmd'
```

```{r}
#| label: insert-service-outreach
#| child: './assets/sections/service_outreach.Rmd'
```

```{r}
#| label: insert-professional-development
#| child: './assets/sections/professional_development.Rmd'
```

```{r}
#| label: insert-professional-memberships
#| child: './assets/sections/professional_memberships.Rmd'
```

```{r}
#| label: insert-additional-interests
#| child: './assets/sections/additional_interests.Rmd'
```

```{r}
#| label: insert-footer
#| child: './assets/sections/footer.Rmd'
```

\bibliographystyle{apalike}
\nobibliography{assets/bib/publications_latex}
